---
title: "Milestone 2"
author: "paolo pasco"
date: "2/14/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Project 1:
#### The Billboard Top 100: An Analysis of Timelessness and Lyrical Content
Katie Cao's 2019 project on [the Billboard Top 100](https://kcao.shinyapps.io/billboard/), analyzes the lyrical content of Billboard hit songs from a period of about sixty years. This project does a lot of things well—the predictions align with common conceptions of pop music (lots of repetition, but unique words to deliver those repeated ideas), and the graphical data is well-presented and easy to understand. Also, according to the project's "about" page, the lyrical data required extensive cleaning to deal with factors like contractions, extraneous labels, and the like, which was very well done. The cons are pretty minor; the fact that different data sets are used for different analyses isn't ideal, but it's understandable given the scope of the project. Also, I'd love more explanation of how the "sentiment analysis" was performed—it's an interesting approach, but I found myself wondering what the methodology was for determining sentiments. Finally, I'm not convinced that "timelessness" is the best way to describe popularity over time, and the fact that it necessitates describing "Party Rock Anthem" as timeless is, quite frankly, insane. I'm sorry, I love LMFAO, but that song is very very fixed to the year 2011 and nothing more.

# Project 2:
#### Hip-Hop's Feelings Towards 2016 Presidential Candidates
Tauheed Islam's 2018 project on [references to presidential candidates in hip-hop](https://tauheed-islam.shinyapps.io/Trump_and_Hip-Hop/), analyzes references to 2016 political candidates (mainly Donald Trump and Hillary Clinton) in a corpus of songs from 1989 to 2016. The project does an interesting job of analysis; references are assigned "positive" or "negative" connotations, as well as categorizations based on the subject of the reference (money, personal life, et cetera). The graphs in the "Takeaway" tab helped demonstrate some interesting trends, such as Trump's popularity in hip-hop shooting down in the late 2010's, as positive references plummet and negative references skyrocket. I had some questions/concerns about the execution of this project. The graphs generated for positive and negative sentiment seem to change depending on whether only positive is displayed, or only negative, or both. The scale of the graphs change based on selection too, which can make it difficult to quickly understand and compare the separate graphs. Also, as in Project 1, not much was explained as to how lyrics were defined as "positive" or "negative"—the best I can assume is that they were assigned by hand, but seeing the data, that's just over 300 song lyrics to analyze, which is a bit inefficient. Is there a better way to accomplish this (i.e., analyzing the words as in Project 1, and developing "positive" and "negative" ratings for each lyric based on the presence of positive or negative sentiments)?
